server:
  port: 9004
  context-path: /sms

  devtools:
    restart:
      enabled: true

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true

