server:
  port: 9001
  context-path: /bos

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: bos
    password: bos
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  devtools:
    restart:
      enabled: true
  http:
    multipart:
      max-file-size: 10Mb

cxf:
  path: /services
  servlet.init:
    service-list-path: /info
  jaxrs:
    component-scan: true

